In [1]:
import numpy as np

In [2]:
a = np.array([[1,6,9],[0,3,3],[8,2,5]])
a

array([[1, 6, 9],
       [0, 3, 3],
       [8, 2, 5]])

a. Swap rows R1<->R2

In [3]:
temp = np.array(a[0])
temp

array([1, 6, 9])

In [4]:
a[0] = a[1]
a[0]

array([0, 3, 3])

In [5]:
a[1] = temp
a[1]

array([1, 6, 9])

In [6]:
a

array([[0, 3, 3],
       [1, 6, 9],
       [8, 2, 5]])

b. Multiply R1 by 5

In [7]:
a[0] = 5 * a[0]
a

array([[ 0, 15, 15],
       [ 1,  6,  9],
       [ 8,  2,  5]])

Subtract row R3 from R1

In [8]:
a[0] = a[0] - a[2]

Final Matrix

In [9]:
a

array([[-8, 13, 10],
       [ 1,  6,  9],
       [ 8,  2,  5]])