In [1]:
import numpy as np

In [2]:
a = np.array([[1,6,9],[-20,3,-3],[8,-13,5]])
a

array([[  1,   6,   9],
       [-20,   3,  -3],
       [  8, -13,   5]])

In [3]:
a[1] = a[1] + 20
a

array([[  1,   6,   9],
       [  0,  23,  17],
       [  8, -13,   5]])

In [4]:
a[2]=a[2]-8
a

array([[  1,   6,   9],
       [  0,  23,  17],
       [  0, -21,  -3]])

In [5]:
a[2] = (a[2]+a[1])
a

array([[ 1,  6,  9],
       [ 0, 23, 17],
       [ 0,  2, 14]])

In [6]:
a[1] = a[1] * 2
a[2] = a[2] * 23
a[2] = a[2] - a[1]
a

array([[  1,   6,   9],
       [  0,  46,  34],
       [  0,   0, 288]])

In [7]:
a[1] = a[1]/46
a

array([[  1,   6,   9],
       [  0,   1,   0],
       [  0,   0, 288]])

In [8]:
a[2] = a[2]/288
a

array([[1, 6, 9],
       [0, 1, 0],
       [0, 0, 1]])